version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_STRING=postgres://homeuser:homepass@localhost:5432/homedb?sslmode=disable
      - HOME_STORAGE_LISTEN_ADDR=:8080
      - JWT_SECRET=supersecret
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: homedb
      POSTGRES_USER: homeuser
      POSTGRES_PASSWORD: homepass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U homeuser -d homedb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge